Repository gardener/ingress-gce, pull requests merged in 2024-09, with the labels that each got.

#1 Multi-platform builds of kubernetes/ingress-gce using github actions
  .github/workflows/release.yaml
  .gitignore
  .reuse/dep5
  Dockerfile
  Makefile
  README.md
Labels: needs/changes, needs/review, size/m

#2 Publish to Google-Artifact-Registry
  .github/workflows/release.yaml
Labels: reviewed/lgtm, needs/review, size/s

#3 change other image-references to GAR to match github-action
  Makefile
  README.md
Labels: reviewed/lgtm, needs/review, size/xs
